#FastDFS配置文件
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 48
    height: 48
  tracker-list:            #TrackerList参数,支持多个
    - xx.xxx.xxx.xxx:xxxxx
